version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mas_salud_backend:latest
    container_name: mas_salud_app
    depends_on:
      - db
    ports:
      - "${PORT}:4000"
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
