export enum EInventoryMovementReason {
  NEW_STOCK_ENTRY = 'NEW_STOCK_ENTRY',
  PRODUCT_DELIVERED = 'PRODUCT_DELIVERED',
  BATCH_DELETED_BY_USER = 'BATCH_DELETED_BY_USER',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
}
